// flow-typed signature: 009e3e65206eb1e84da7a96f56a09543
// flow-typed version: <<STUB>>/@accounts/accounts_vgit+https://github.com/js-accounts/accounts.git#git-package/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@accounts/accounts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@accounts/accounts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@accounts/accounts/lib/index' {
  declare module.exports: any;
}

declare module '@accounts/accounts/src/client/AccountsClient' {
  declare module.exports: any;
}

declare module '@accounts/accounts/src/client/AccountsClient.spec' {
  declare module.exports: any;
}

declare module '@accounts/accounts/src/client/createStore' {
  declare module.exports: any;
}

declare module '@accounts/accounts/src/client/module' {
  declare module.exports: any;
}

declare module '@accounts/accounts/src/client/store' {
  declare module.exports: any;
}

declare module '@accounts/accounts/src/common/AccountsCommon' {
  declare module.exports: any;
}

declare module '@accounts/accounts/src/common/defaultConfigs' {
  declare module.exports: any;
}

declare module '@accounts/accounts/src/common/errors' {
  declare module.exports: any;
}

declare module '@accounts/accounts/src/common/passwordSignupFields' {
  declare module.exports: any;
}

declare module '@accounts/accounts/src/common/toUsernameAndEmail' {
  declare module.exports: any;
}

declare module '@accounts/accounts/src/common/toUsernameAndEmail.spec' {
  declare module.exports: any;
}

declare module '@accounts/accounts/src/common/UserObjectType' {
  declare module.exports: any;
}

declare module '@accounts/accounts/src/index' {
  declare module.exports: any;
}

declare module '@accounts/accounts/src/server/AccountsServer' {
  declare module.exports: any;
}

declare module '@accounts/accounts/src/server/AccountsServer.spec' {
  declare module.exports: any;
}

declare module '@accounts/accounts/src/server/DBDriver' {
  declare module.exports: any;
}

declare module '@accounts/accounts/wallaby' {
  declare module.exports: any;
}

declare module '@accounts/accounts/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module '@accounts/accounts/lib/index.js' {
  declare module.exports: $Exports<'@accounts/accounts/lib/index'>;
}
declare module '@accounts/accounts/src/client/AccountsClient.js' {
  declare module.exports: $Exports<'@accounts/accounts/src/client/AccountsClient'>;
}
declare module '@accounts/accounts/src/client/AccountsClient.spec.js' {
  declare module.exports: $Exports<'@accounts/accounts/src/client/AccountsClient.spec'>;
}
declare module '@accounts/accounts/src/client/createStore.js' {
  declare module.exports: $Exports<'@accounts/accounts/src/client/createStore'>;
}
declare module '@accounts/accounts/src/client/module.js' {
  declare module.exports: $Exports<'@accounts/accounts/src/client/module'>;
}
declare module '@accounts/accounts/src/client/store.js' {
  declare module.exports: $Exports<'@accounts/accounts/src/client/store'>;
}
declare module '@accounts/accounts/src/common/AccountsCommon.js' {
  declare module.exports: $Exports<'@accounts/accounts/src/common/AccountsCommon'>;
}
declare module '@accounts/accounts/src/common/defaultConfigs.js' {
  declare module.exports: $Exports<'@accounts/accounts/src/common/defaultConfigs'>;
}
declare module '@accounts/accounts/src/common/errors.js' {
  declare module.exports: $Exports<'@accounts/accounts/src/common/errors'>;
}
declare module '@accounts/accounts/src/common/passwordSignupFields.js' {
  declare module.exports: $Exports<'@accounts/accounts/src/common/passwordSignupFields'>;
}
declare module '@accounts/accounts/src/common/toUsernameAndEmail.js' {
  declare module.exports: $Exports<'@accounts/accounts/src/common/toUsernameAndEmail'>;
}
declare module '@accounts/accounts/src/common/toUsernameAndEmail.spec.js' {
  declare module.exports: $Exports<'@accounts/accounts/src/common/toUsernameAndEmail.spec'>;
}
declare module '@accounts/accounts/src/common/UserObjectType.js' {
  declare module.exports: $Exports<'@accounts/accounts/src/common/UserObjectType'>;
}
declare module '@accounts/accounts/src/index.js' {
  declare module.exports: $Exports<'@accounts/accounts/src/index'>;
}
declare module '@accounts/accounts/src/server/AccountsServer.js' {
  declare module.exports: $Exports<'@accounts/accounts/src/server/AccountsServer'>;
}
declare module '@accounts/accounts/src/server/AccountsServer.spec.js' {
  declare module.exports: $Exports<'@accounts/accounts/src/server/AccountsServer.spec'>;
}
declare module '@accounts/accounts/src/server/DBDriver.js' {
  declare module.exports: $Exports<'@accounts/accounts/src/server/DBDriver'>;
}
declare module '@accounts/accounts/wallaby.js' {
  declare module.exports: $Exports<'@accounts/accounts/wallaby'>;
}
declare module '@accounts/accounts/webpack.config.js' {
  declare module.exports: $Exports<'@accounts/accounts/webpack.config'>;
}
